name: Label Verified PRs

on:
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  label:
    runs-on: ubuntu-22.04
    if: github.event.pull_request.merged == false

    steps:
    - name: Add '✅ Verified' label if verify passes
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const checks = await github.checks.listForRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: context.payload.pull_request.head.sha,
          });
          const passed = checks.data.check_runs.every(check => check.conclusion === "success");
          if (passed) {
            await github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ["✅ Verified"],
            });
          }
