name: Ruby

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Ruby ${{ matrix.ruby }}

    strategy:
      matrix:
        ruby:
          - '3.3.0'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler: '2.4'
        bundler-cache: true

    - name: Clean old gem artifacts
      run: rm -f *.gem

    - name: Install dependencies
      run: |
        bundle config set path 'vendor/bundle'
        bundle install --jobs 4 --retry 3

    - name: Check code style (StandardRB)
      run: bundle exec rake standard

    - name: Build gem
      run: bundle exec rake build

    - name: Run tests (if any)
      run: |
        if [ -f Rakefile ]; then
          bundle exec rake
        else
          echo "No Rakefile found, skipping tests."
        fi
