name: Verify Gem and Formatting

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-22.04
    name: Verify Gem and Formatting

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.0'
        bundler-cache: true
        cache-version: 0
      continue-on-error: true  # ignore minor cache save conflicts

    - name: Install and verify gems
      run: |
        echo "🔧 Installing gems..."
        bundle config set path vendor/bundle
        bundle install --jobs 4 --retry 3

        echo "🔎 Verifying installed gems and Gemfile.lock sync..."
        bundle check

    - name: Run StandardRB formatting check
      run: |
        echo "🎨 Checking Ruby style..."
        bundle exec rake standard
